---
- name: set instance data
  set_fact:
    instance_data: "{{ instances[hostvars[inventory_hostname].instance_name] }}"
  tags:
   - always

- name: set instance name
  set_fact:
    instance_name: "{{ hostvars[inventory_hostname].instance_name }}"
  tags:
   - always

- include_tasks: install_neutron_plugin.yml
  name: install neutron plugin
  when:
    - roles[instance_name].openstack is defined 
  tags:
   - plugin
