---
- name: run compute plugin docker 
  shell: docker run -d --rm --network="host" --privileged -v /usr/lib/python2.7:/opt/plugin {{ container_registry }}/{{ item }}:{{ contrail_version_tag }}
  with_items:
    - contrail-openstack-compute-init

- name: set service_metadata_proxy
  replace:
    path: /etc/nova/nova.conf
    regexp: 'service_metadata_proxy.*false'
    replace: 'service_metadata_proxy = true'
    backup: yes

- name: set metadata_proxy_shared_secret
  replace:
    path: /etc/nova/nova.conf
    regexp: 'metadata_proxy_shared_secret.*='
    replace: 'metadata_proxy_shared_secret = contrail'

- name: restart nova compute on compute node
  service:
    name: openstack-nova-compute
    state: restarted
