---
- name: set instance data
  set_fact:
    instance_data: "{{ instances[hostvars[inventory_hostname].instance_name] }}"
  tags:
   - always

- name: set instance name
  set_fact:
    instance_name: "{{ hostvars[inventory_hostname].instance_name }}"
  tags:
   - always

- name: destroy redis
  docker_service:
    project_src: /etc/contrail/redis
    state: absent
  when: roles[instance_name].webui is defined or roles[instance_name].analytics is defined
  tags:
    - webui
    - analytics

- name: destroy contrail config database
  docker_service:
    project_src: /etc/contrail/config_database
    state: absent
  when: roles[instance_name].config_database is defined
  tags:
    - config_database

- name: destroy contrail config
  docker_service:
    project_src: /etc/contrail/config
    state: absent
  when: roles[instance_name].config is defined
  tags:
    - config

- name: destory contrail webui
  docker_service:
    project_src: /etc/contrail/webui
    state: absent
  when: roles[instance_name].webui is defined
  tags:
    - webui

- name: destroy contrail control
  docker_service:
    project_src: /etc/contrail/control
    state: absent
  when: roles[instance_name].control is defined
  tags:
   - control

#- name: destroy contrail control_only
#  docker_service:
#    project_src: /etc/contrail/control
#    state: absent
#  include: create_control_only.yml
#  when: roles[instance_name].control_only is defined
#  tags:
#    - control_only

- name: destroy contrail analytics database
  docker_service:
    project_src: /etc/contrail/analytics_database
    state: absent
  when: roles[instance_name].analytics_database is defined
  tags:
    - analytics_database

- name: destroy contrail analytics
  docker_service:
    project_src: /etc/contrail/analytics
    state: absent
  when: roles[instance_name].analytics is defined
  tags:
    - analytics

#- name: create cni
#  docker_service:
#    project_src: /etc/contrail/analytics
#    state: absent
#  include: create_k8s_cni.yml
#  when: roles[instance_name].k8s_node is defined
#  tags:
#    - k8s
#
#- name: configure k8s for Contrail
#  include: configure_k8s.yml
#  when: roles[instance_name].k8s_master is defined and k8s_master_name is defined and inventory_hostname == k8s_master_name
#  tags:
#    - k8s

- name: destroy contrail vrouter
  docker_service:
    project_src: /etc/contrail/vrouter
    state: absent
  when: roles[instance_name].vrouter is defined
  tags:
    - vrouter

- name: destroy contrail vrouter
  shell: docker rm -f `docker ps -qa`
  when: roles[instance_name].vrouter is defined
  tags:
    - vrouter
  ignore_errors: yes

- name: remove docker images 
  shell: docker rmi `docker images -q`
  tags:
    - remove_images
  ignore_errors: yes
