---
- name: run plugin docker once
  shell: docker run -d --rm --network="host" -v /usr/lib/python2.7:/opt/plugin {{ container_registry }}/{{ item }}:{{ contrail_version_tag }}
  with_items:
    - contrail-openstack-neutron-init
  run_once: yes

- name: set contrail core plugin
  replace:
    path: /etc/neutron/neutron.conf
    regexp: '^core_plugin=.*'
    replace: 'core_plugin=neutron_plugin_contrail.plugins.opencontrail.contrail_plugin.NeutronPluginContrailCoreV2'

- name: set service plugins
  replace:
    path: /etc/neutron/neutron.conf
    regexp: '^service_plugins=.*'
    replace: 'service_plugins=neutron_plugin_contrail.plugins.opencontrail.loadbalancer.v2.plugin.LoadBalancerPluginV2'

- name: set api extension path
  replace:
    path: /etc/neutron/neutron.conf
    regexp: '.*api_extensions_path.*'
    replace: 'api_extensions_path = /usr/lib/python2.7/site-packages/neutron_plugin_contrail/extensions:/usr/lib/python2.7/site-packages/neutron_lbaas/extensions'

#- name: set quota driver
#  replace:
#    path: /etc/neutron/neutron.conf
#    regexp: '.*quota_driver.*'
#    replace: 'neutron_plugin_contrail.plugins.opencontrail.quota.driver.QuotaDriver'

- name: create contrail plugin directory
  file:
    path: /etc/neutron/plugins/opencontrail
    owner: neutron
    group: neutron
    state: directory

- name: copy contrail plugin
  template:
    src: ContrailPlugin.ini.j2
    dest: /etc/neutron/plugins/opencontrail/ContrailPlugin.ini
    owner: neutron
    group: neutron

- name: link contrail plugin
  file:
    src: /etc/neutron/plugins/opencontrail/ContrailPlugin.ini
    dest: /etc/neutron/plugin.ini
    owner: neutron
    group: neutron
    state: link

- name: restart neutron server
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - neutron-server

- name: set service_metadata_proxy in nova.conf
  replace:
    path: /etc/nova/nova.conf
    regexp: 'service_metadata_proxy.*false'
    replace: 'service_metadata_proxy = true'
    backup: yes

- name: set metadata_proxy_shared_secret in nova.conf
  replace:
    path: /etc/nova/nova.conf
    regexp: 'metadata_proxy_shared_secret.*='
    replace: 'metadata_proxy_shared_secret = contrail'

- name: restart nova services
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - openstack-nova-api
    - openstack-nova-conductor
    - openstack-nova-scheduler
    - openstack-nova-consoleauth

