provider_config:
  bms:
    #ssh_pwd: blade123
    ssh_user: heat-admin
    ssh_private_key: ~/.ssh/id_rsa
    #ntpserver: pool.ntp.org
    domainsuffix: local
instances:
  bms1:
    provider: bms
    ip: 172.30.5.10
    roles:
        config_database:
        config:
        control:
        analytics_database:
        analytics:
        webui:
        openstack:
    #neutron_config_dir: /etc/kolla/neutron-server
    neutron_config_dir: /var/lib/config-data/puppet-generated/neutron/etc/neutron
    #neutron_container_name: neutron_server
    neutron_container_name: neutron_api
  bms2:
    provider: bms
    ip: 172.30.5.16
    roles:
        vrouter:
        openstack_compute:
    #nova_config_dir: /etc/kolla/nova-compute
    nova_config_dir: /var/lib/config-data/puppet-generated/nova_libvirt/etc/nova
    nova_compute_container_name: nova_compute
  bms3:
    provider: bms
    ip: 172.30.5.12
    roles:
        vrouter:
        openstack_compute:
    #nova_config_dir: /etc/kolla/nova-compute
    nova_config_dir: /var/lib/config-data/puppet-generated/nova_libvirt/etc/nova
    nova_compute_container_name: nova_compute
global_configuration:
  CONTAINER_REGISTRY: 10.240.230.100:5000
  #REGISTRY_PRIVATE_INSECURE: True
contrail_configuration:
  CONFIG_DTABASE_NODEMGR__DEFAULTS__minimum_diskGB: "1"
  CONFIG_NODEMGR__DEFAULTS__minimum_diskGB: "1"
  DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: "1"
  CONTRAIL_VERSION: tfr5_lenovo0012
  OPENSTACK_VERSION: queens
  CLOUD_ORCHESTRATOR: openstack
  RABBITMQ_NODE_PORT: 5673
  VROUTER_GATEWAY: 192.168.120.1
  PHYSICAL_INTERFACE: vlan505
  AUTH_MODE: keystone
  KEYSTONE_AUTH_HOST: 192.168.100.10
  KEYSTONE_AUTH_PUBLIC_PORT: 9696
  KEYSTONE_AUTH_URL_VERSION: /v3
  KEYSTONE_AUTH_ADMIN_USER: admin
  KEYSTONE_AUTH_ADMIN_PASSWORD: dJBnUQwQjsmB8w8HYQEKFFymv
  KEYSTONE_AUTH_REGION_NAME: regionOne
  CONTROLLER_NODES: &contrail_ctrl_ip 192.168.100.22
  CONTROL_NODES: *contrail_ctrl_ip
kolla_config:
  kolla_globals:
    enable_haproxy: no
    enable_ironic: no
    enable_swift: no
    kolla_internal_vip_address: 192.168.100.10
  kolla_passwords:
    keystone_admin_password: dJBnUQwQjsmB8w8HYQEKFFymv
