provider_config:
  bms:
    #ssh_pwd: blade123
    ssh_user: heat-admin
    ssh_private_key: ~/.ssh/id_rsa
    #ntpserver: pool.ntp.org
    #domainsuffix: local
instances:
  bms1:
    provider: bms
    ip: 172.30.5.9
    roles:
        config_database:
        config:
        control:
        analytics_database:
        analytics:
        webui:
        openstack:
  bms2:
    provider: bms
    ip: 172.30.5.16
    roles:
        vrouter:
        openstack_compute:
  bms3:
    provider: bms
    ip: 172.30.5.8
    roles:
        vrouter:
        openstack_compute:
global_configuration:
  CONTAINER_REGISTRY: 10.240.230.100:5000
  #REGISTRY_PRIVATE_INSECURE: True
contrail_configuration:
  neutron_config_dir: /var/lib/config-data/puppet-generated/neutron/etc/neutron/
  neutron_config_dir_root: /var/lib/config-data/puppet-generated/neutron/
  neutron_container_name: neutron_api
  nova_config_dir: /var/lib/config-data/puppet-generated/nova_libvirt/etc/nova/
  nova_config_dir_root: /var/lib/config-data/puppet-generated/nova_libvirt/
  nova_compute_container_name: nova_compute
  CONFIG_DTABASE_NODEMGR__DEFAULTS__minimum_diskGB: "1"
  CONFIG_NODEMGR__DEFAULTS__minimum_diskGB: "1"
  DATABASE_NODEMGR__DEFAULTS__minimum_diskGB: "1"
  WEBUI_LISTEN_ADDRESSES: "'0.0.0.0'"
  CONTRAIL_VERSION: tfr5_lenovo0015
  OPENSTACK_VERSION: queens
  CLOUD_ORCHESTRATOR: openstack
  RABBITMQ_NODE_PORT: 5673
  REDIS_SERVER_PORT: 6378
  VROUTER_GATEWAY: 192.168.120.1
  AUTH_MODE: keystone
  KEYSTONE_AUTH_HOST: 172.30.5.13
  KEYSTONE_AUTH_PUBLIC_PORT: 35357
  KEYSTONE_AUTH_URL_VERSION: /v3
  KEYSTONE_AUTH_ADMIN_USER: admin
  KEYSTONE_AUTH_ADMIN_PASSWORD: dJBnUQwQjsmB8w8HYQEKFFymv
  KEYSTONE_AUTH_REGION_NAME: regionOne
  CONTROLLER_NODES: 192.168.100.19
  CONTROL_NODES: 192.168.120.19
kolla_config:
  kolla_globals:
    enable_haproxy: no
    enable_ironic: no
    enable_swift: no
    kolla_internal_vip_address: 172.30.5.13
  kolla_passwords:
    keystone_admin_password: dJBnUQwQjsmB8w8HYQEKFFymv
