# orchestrator MUST be passed as a command line argument like so:
#
# ansible-playbook -i inventory/ -e orchestrator=none playbook/install_contrail_plugin.yml
#
#
- name: Create container host group
  hosts: localhost
  connection: local
  gather_facts: no
  pre_tasks:
    - name: Expose instances
      set_fact:
          instances: "{{ instances }}"
      when: hostvars['localhost']['instances'] is undefined
  roles:
    - name: Generate container_host group
      role: create_container_host_group
    - name: Generate openstack host groups
      role: create_openstack_host_group
  vars_files:
    - "{{ config_file }}"

- name: Install Contrail Plugin
  hosts: container_hosts
  gather_facts: no
  roles:
  - { role: install_contrail_plugin, when: skip_contrail is not defined or not skip_contrail|bool }
  vars_files:
  - "{{ hostvars['localhost'].config_file }}"
  environment:
   - https_proxy: "{{ contrail_configuration.HTTPS_PROXY|default('') }}"
   - http_proxy: "{{ contrail_configuration.HTTP_PROXY|default('') }}"

